GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "new blog 1",
    "author": "new author 1",
    "url": "some/url/1",
    "likes": 4,
    "userId": "6096b8fe885b8f22f6fdb5b5"
}

###
DELETE http://localhost:3001/api/blogs/608d617c711c10e060a50fac

###
PUT http://localhost:3001/api/blogs/5a422a851b54a676234d17f7
Content-Type: application/json

{
   "title": "new updated blog 1",
    "author": "new updated author 1",
    "url": "some/url/1",
    "likes": 40
}

###
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "username": "username2",
    "name": "Jane Doe",
    "password": "Password"
}

###
GET http://localhost:3001/api/users/

###
POST http://localhost:3001/api/login/
Content-Type: application/json

{
    "username": "username2",
    "password": "Password"
}


 