GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMSIsIm5hbWUiOiJKb2huIERvZSIsImlkIjoiNjA5OWVkODY2NGRhOWEyZWY5ZmMzYTQ5IiwiaWF0IjoxNjIwNzYxNzMxfQ.W1ZrU2rUyRoJDejl_tq6BYoGkrqj5whPwebgBx7myEM

{
    "title": "new blog 2",
    "author": "new author 1",
    "url": "some/url/1",
    "likes": 4,
    "userId": "6099e3779103f42c9c0f0046"
}

###
DELETE http://localhost:3001/api/blogs/6099ee211dd09d2f5b14a696

###
PUT http://localhost:3001/api/blogs/5a422a851b54a676234d17f7
Content-Type: application/json

{
   "title": "new updated blog 1",
    "author": "new updated author 1",
    "url": "some/url/1",
    "likes": 40
}

###
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "username": "username1",
    "name": "John Doe",
    "password": "Password"
}

###
GET http://localhost:3001/api/users/

###
POST http://localhost:3001/api/login/
Content-Type: application/json

{
    "username": "username1",
    "password": "Password"
}


 